<?php
$collection = $this->getHelloCollection();
?>
<form action="<?php echo $this->getUrl("hello/add/index")?>" method="post">
  <div class="form-group">
    <label for="name">Add your name:</label>
    <input type="name" class="input" name="name" id="name">
    <button type="submit" class="btn btn-default">Submit</button>
  </div>
</form>
<table class="table">
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Created At</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($collection as $item): ?>  
      <tr>
        <td><?php echo $item->getId();?></td>
        <td><?php echo $item->getName();?></td>
        <td><?php echo $item->getCreatedAt();?></td>
      </tr>
    <?php endforeach; ?>  
    </tbody>
</table>